name: Build React on S3
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master  # リポジトリをチェックアウト

      - name: Install Dependencies
        run: |
          cd frontend
          yarn install

      - name: Build
        run: |
          cd app/frontend
          yarn build  # React ビルド

      - name: Deploy  # S3にデプロイ
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY_ID }}
        run: |
          aws s3 cp --recursive --region ap-northeast-1 app/backend/views s3://static-novelchain
